### ISSUE TITLE
Does it work under Docker?

### ISSUE THREAD

**Issue by Fookiwara** [swaggo/http-swagger#11]
Hello,
I try to dokerize a simple application but it seems to fail: the url http://localhost:1323/doc/index.html returns a ERR_CONNECTION_REFUSED. Any Idea?
Here is my dockerfile:

FROM golang:alpine AS builder
RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/testSwagger/
COPY . .
RUN go get -d -v
RUN go build -o /go/bin/testSwagger

FROM alpine:latest
COPY --from=builder /go/bin/testSwagger /
CMD ["/testSwagger"]

EXPOSE 1323

**Comment by OberstK** [comment]
Did you map the port on the run of the docker container? Because this could also just be a docker issue and not with the swagger lib
