### ISSUE TITLE
swagger/index.html loads a default swagger/doc.json but not docs/swagger.json

### ISSUE THREAD

**Issue by yizeng** [swaggo/http-swagger#110]
I have been facing this issue but not sure which steps I have missed.

Going through the steps in README, I have successfully

- generated `docs/swagger.json` with the correct routes using `swag init` command 
- had http://localhost:1323/swagger/index.html up and running.

But it loads a default template `doc.json` from URL http://localhost:1323/swagger/doc.json, not the JSON file generated under `docs/swagger.json`.

```json
{
    "schemes": [],
    "swagger": "2.0",
    "info": {
        "description": "This is a sample server Petstore server.",
        "title": "Swagger Example API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "petstore.swagger.io",
    "basePath": "/v2",
    "paths": {}
}
```

I can use a workaround to serve `docs/swagger.json` as a static file and load the JSON file from http://localhost:1323/docs/swagger.json instead of http://localhost:1323/swagger/doc.json.
But I assume this shouldn't be the way to go.

```go
fileServer := http.FileServer(http.Dir("./docs/"))
r.Handle("/docs/swagger.json", http.StripPrefix("/docs", fileServer))
r.Get("/swagger/*", httpSwagger.Handler(
    httpSwagger.URL("http://localhost:1323/docs/swagger.json"), // The url pointing to API definition
))
```

Environment:

- Go 1.20
- swaggo/http-swagger v1.3.4
- swaggo/swag v1.16.2
- go-chi/chi/v5 v5.0.10

**Comment by yizeng** [comment]
Sorted!

It turned out I copied the example from this repo's README with

```
_ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
```

But it should really be the path of my own `/docs`, like `_ "example-module-name/docs"`.

The [swaggo/swag](https://github.com/swaggo/swag) README has a better-documented example which is more obvious.

```
"./docs" // docs is generated by Swag CLI, you have to import it.
```

**Comment by bschaatsbergen** [comment]
This took way to long to find, ran into the same issue as I blindly copy pasted the code (as suggested in the README)... thanks for pointing out @yizeng lol.
