### ISSUE TITLE
Question: Is it possible not one docs dir? Not one Register

### ISSUE THREAD

**Issue by remotejob** [swaggo/http-swagger#111]
`
_ "gitlab.com/golang_development/stand-alone-swagger/docs" // docs is generated by Swag CLI, you have to import it.
_ "gitlab.com/golang_development/stand-alone-swagger/testdocs"
`

`panic: Register called twice for swag: swagger`

**Comment by ubogdan** [comment]
There is a parameter `--instanceName`  that allows you to change the age of the instance; when not provided, the name is swag, and you can't register two definitions with the same name.

**Comment by remotejob** [comment]
Ok I did (using --instanceName 2 instaces **apiserver, wssgok8smodulev2**)
`_ "gitlab.com/golang_development/stand-alone-swagger/docs/wss-go-k8s-module-v2"`
`_ "gitlab.com/golang_development/stand-alone-swagger/docs/apiserver"`

I can't figure out how to make routing

r.Get("/swagger1/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:1323/swagger/docs/apiserver_docs.json"), //The url pointing to API definition
	))


r.Get("/swagger2/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:1323/swagger/docs/wssgok8smodulev_docs.json"), 
	))

**Comment by remotejob** [comment]
Ok resolved by httpSwagger.InstanceName("apiserver")
