### ISSUE TITLE
Report refresh page bug

### ISSUE THREAD

**Issue by foolin** [swaggo/http-swagger#14]
When click a method, the following bug appears when refreshing the page：

![image](https://user-images.githubusercontent.com/2344587/54873529-c7cd2900-4e12-11e9-8ed2-36233c76aab3.png)

**Comment by easonlin404** [comment]
@pei0804 would you help check it? Thx.

**Comment by pei0804** [comment]
ok.

**Comment by pei0804** [comment]
I find bug from `url: document.location.href.replace("index.html", "") + "doc.json",`.
https://github.com/swaggo/http-swagger/blob/200858b15f6bb106c0d8225b8f1ec3fb6618524d/swagger.go#L119

![image](https://user-images.githubusercontent.com/9821370/54879914-31385080-4e82-11e9-8d34-c95f845c051f.png)
but I have not good idea.

**Comment by pei0804** [comment]
I fix it. 
@foolin

**Comment by foolin** [comment]
Good! Thx!
