### ISSUE TITLE
support go module

### ISSUE THREAD

**Issue by pei0804** [swaggo/http-swagger#17]

**Comment by cescoferraro** [comment]
> build github.com/b2breservas/api: cannot load github.com/swaggo/http-swagger/example/docs: cannot find module providing package github.com/swaggo/http-swagger/example/docs

**Comment by cescoferraro** [comment]
@pei0804 forking the project without any modification to the code base made it work for me
IDKY

**Comment by pei0804** [comment]
I see. thank you!

**Comment by bruceadowns** [comment]
see PR https://github.com/swaggo/http-swagger/pull/24
