### ISSUE TITLE
No operations defined in spec!

### ISSUE THREAD

**Issue by dexchen** [swaggo/http-swagger#23]
when run the sample go-chi (without any modification), and access the index.html, "No operations defined in spec!" is shown in the ui, and there is no API doc shown in swagger UI.

Running in latest Chrome.

**Comment by dexchen** [comment]
It is not an real issue. It is confused by the readme doc which does not match the real code which does not have any specific APIs.

**Comment by ubogdan** [comment]
Even you forgot to include the generated goc.go, even your doc.json is not accessible via HTTP. Please see [this](https://github.com/swagger-api/swagger-ui/issues/2757) for reference.
