### ISSUE TITLE
Work with Gorilla mux

### ISSUE THREAD

**Issue by ricmalta** [swaggo/http-swagger#3]
Hi, I'm quite newbie to the Go ecosystems and I chose Gorilla mux to start a new HTTP API.
However I can't figure it out how to use it with the gorilla muxer.

Anyone could help me out with a basic implementation?

**Comment by pei0804** [comment]
OK. I create example.

**Comment by nltommynl** [comment]
> Hi, I'm quite newbie to the Go ecosystems and I chose Gorilla mux to start a new HTTP API.
However I can't figure it out how to use it with the gorilla muxer.

> Anyone could help me out with a basic implementation?

Me too, but i will try ;-)

1. Just start with adding comments to your API source code (like this: https://github.com/swaggo/http-swagger#canonical-example)
2. Download swag
`go get github.com/swaggo/swag/cmd/swag`
3. Run swag (it will generate some files in a docs/ directory)
`swag init`
4. Add some import statements
`"github.com/swaggo/http-swagger"`
`_"your/doc/location/docs"`
5. Setup a new mux router and add a swagger handler
`router := mux.NewRouter()`
`router.PathPrefix("/documentation/").Handler(httpSwagger.WrapHandler)`

A few features do not work, i'm not sure if its related to mux.
1. @securityDefinitions does not work
2. doc.json link will open a black new page

**Comment by pei0804** [comment]
https://github.com/swaggo/http-swagger/pull/4
I created.

**Comment by ricmalta** [comment]
It works 🍺
However it needs some care to be more easy to integrate. 
I'm a but supporter of swagger docs, I'll try to contribute to the project as much as possible.

**Comment by asaberwd** [comment]
it only parse general api info not parsing api operations comments !

**Comment by mhmdhsnkml** [comment]
![image](https://user-images.githubusercontent.com/22633217/83965130-99ceea00-a8db-11ea-9766-4b589263ae1c.png)

it return raw html.

```
// App structure contains (Router, and DB)
type App struct {
	Router *mux.Router
}

.......

func (a *App) initializeRoutes() {
	a.Router.Use(middlewares.SetContentTypeMiddleware)

	a.Router.HandleFunc("/", home).Methods("GET")
	a.Router.HandleFunc("/register", a.UserSignUp).Methods("POST")
	a.Router.HandleFunc("/login", a.Login).Methods("POST")

	a.Router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
}
```
and i already add `_"your/doc/location/docs"`

**Comment by phattv** [comment]
@mhmdhsnkml you should check your response Content-Type, looks like it's `application/json`, remove the header and it should work
