### ISSUE TITLE
go-chi paths not being detected

### ISSUE THREAD

**Issue by BrendanThompson** [swaggo/http-swagger#30]
I have the following code, which will return the root swagger, but it does not go into the routes themselves.

```go
// @title Example
// @version v0.0.0
func main() {
  r := chi.NewRouter()
  r.Mount("/things", thing.Handler{}.Routes())
  r.Get("/swagger/*", httpSwagger.Handler(
    httpSwagger.URL("http://localhost:8000/swagger/doc.json"),
  ))

  err = http.ListenAndServe(":8000", r)
  if err != nil {
    log.Fatal(err)
  }
}
```

However, my handler which lives in `./api/thing/handler.go` which has the following code will not show in the `swagger.json`, or in the UI.

```go
// Get godoc
// @Summary gets a thing
// @Accept json
// @Produce json
// @Success 200
func (h Handler) Get(w http.ResponseWriter, r *http.Request) {
  t := &Thing{}
  t.ID = helpers.GetIDFromRequest(r)
  t.Get()

  helpers.RespondSuccess(w, t)
}
```

Not too sure how to get this one to work unfortunately.

**Comment by BrendanThompson** [comment]
@sdghchj @easonlin404 wondering if you've any insight here?

**Comment by sdghchj** [comment]
@router is the key comment line, but you omitted it

**Comment by BrendanThompson** [comment]
@sdghchj where does one add `@router`?

**Comment by sdghchj** [comment]
> @sdghchj where does one add `@router`?

you had better read examples in README.md.

```
// @Description Get godoc
// @Summary gets a thing
// @Accept json
// @Produce json
// @Router /swagger/ [GET]
// @Success 200
func (h Handler) Get(w http.ResponseWriter, r *http.Request) {
  t := &Thing{}
  t.ID = helpers.GetIDFromRequest(r)
  t.Get()

  helpers.RespondSuccess(w, t)
}
```

**Comment by BrendanThompson** [comment]
@sdghchj the `README.md` of the `http-swagger` repo is not overly clear to be honest, I wasn't 100% that this would be an exact replica of what is described in the `swag` repo. Thus, I queried to ensure that the data received was correct 😄
