### ISSUE TITLE
Swagger UI is not rendering on my localhost?

### ISSUE THREAD

**Issue by grecinto** [swaggo/http-swagger#56]
Hi, I followed instructions to annotate, generate and to host the swagger UI displaying my "docs". But the HTML string gets displayed on my browser, not being rendered.

What could possibly be causing this? How to fix?

**Comment by ubogdan** [comment]
@grecinto We will be more than happy to give you a hand here, but the provided details don't give us any clue what can be wrong.

**Comment by grecinto** [comment]
Ok I have clue. Lol.
seriously, I don’t need the help on this anymore.

If you or anybody can help on my other question on how to support Array of Objects payload on the Post Request body, that would really help.

thanks for the kind response.
