### ISSUE TITLE
Different exibition when single struct or a array of structs

### ISSUE THREAD

**Issue by VitorinoAssuncao** [swaggo/http-swagger#60]
Hi people, wanted to know if is intentional or a possible bug, because I'm having some troubles when trying to show a single struct, like in the example bellow:

`type PurchaseOutput struct {
	// Identificador da proposta no formato UUID
	ID string `json:"id" example:"6f1d7913-0a3b-41a0-93ce-0027aff9d1d2"`

	// Status of Purchase
	Status lang.TranslatedString `json:"status"`

	// List of the products in this purchase
	Products []products.ProductOutput `json:"products``

The first struct, lang.TranslatedString, don't show the value of description in the documentation, even tough in the file doc, he correctly appear. In the same time, the array of strings, load the description correct.

**Comment by ubogdan** [comment]
This issue is not related to http-swagger. 

Duplicated https://github.com/swaggo/swag/issues/1166.
