### ISSUE TITLE
Blank page on Go-chi example

### ISSUE THREAD

**Issue by oliverasistemas** [swaggo/http-swagger#98]
When trying go-chi example https://github.com/swaggo/http-swagger/tree/master/example/go-chi I get a blank page. 

`Refused to apply style from 'http://localhost:1323/swagger/swagger-ui.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled. `
The issue seems to be V2 as if I try the example as is before https://github.com/swaggo/http-swagger/pull/97 it works fine.

**Comment by ubogdan** [comment]
@oliverasistemas I found the issue , unfortunately github is experiencing some trouble and I'm not able to push

https://www.githubstatus.com/

```shell
$ git push origin fix
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 12 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 2.01 KiB | 514.00 KiB/s, done.
Total 8 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
remote: fatal error in commit_refs
To github.com:swaggo/http-swagger.git
 ! [remote rejected] fix -> fix (failure)
error: failed to push some refs to 'git@github.com:swaggo/http-swagger.git'
```
